---
env:
  - "PUPPET_VERSION='~> 4.5' BEAKER_set=centos7"
  - "PUPPET_VERSION='~> 4.5' BEAKER_set=ubuntu1404"
language: ruby
rvm:
  - 2.3.1
cache: bundler
before_install: rm Gemfile.lock || true
bundler_args: --without development
dist: trusty
sudo: required
script: 
  - "bundle exec rake metadata_lint"
  - "bundle exec rubocop"
  - "bundle exec rake lint"
  - "bundle exec rake validate"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
  - "bundle exec rake acceptance"
notifications:
  email: false
